# Generated by Django 4.0.3 on 2022-07-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_total_price_alter_cartitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
